### ISSUE TITLE
Remove dependency on xenstore

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-xen#3]
copied from https://github.com/mirage/mirage-platform/issues/90 by @djs55 

Now that blkif and netif are out-of-tree, it should be possible to remove the dependency on xenstore. We would need to add some kind of pre-suspend hook (xenstore is the only service which is shutdown pre-suspend, everything else just re-issues requests post-resume); and functorise netif over xenstore (like blkif).

**Comment by mato** [comment]
No longer relevant with #23
